import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/banner'
const inter = Inter({ subsets: ['latin'] })
import NavBar from '@/components/navBar'
import Card from '@/components/card/card.js'
import SectionCards from "../components/card/section-cards";

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <NavBar username="ajayverma041999@gmail.com"/>
      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/animal.webp"
      />
      
      <SectionCards title="Disney" />
      


    </>
  )
}
